# Generated by Django 5.2.8 on 2025-11-17 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id_agenda', models.AutoField(primary_key=True, serialize=False)),
                ('dia_atencion', models.DateField()),
                ('hora_atencion', models.TimeField()),
                ('inicio_almuerzo', models.TimeField(blank=True, null=True)),
                ('fin_almuerzo', models.TimeField(blank=True, null=True)),
                ('duracion_turno', models.DurationField()),
                ('fecha_creacion_agenda', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_actualizacion_agenda', models.DateTimeField(auto_now=True, null=True)),
                ('id_usuario_creacion_agenda', models.IntegerField(blank=True, null=True)),
                ('id_usuario_actualizacion_agenda', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Agenda',
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_compra', models.DateTimeField()),
                ('total_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('estado_pago', models.CharField(max_length=50)),
                ('fecha_creacion_compra', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_actualizacion_compra', models.DateTimeField(auto_now=True, null=True)),
                ('id_usuario_creacion_compra', models.IntegerField(blank=True, null=True)),
                ('id_usuario_actualizacion_compra', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Compra',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_estado', models.CharField(max_length=100)),
                ('fecha_creacion_estado', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_actualizacion_estado', models.DateTimeField(auto_now=True, null=True)),
                ('id_usuario_creacion_estado', models.IntegerField(blank=True, null=True)),
                ('id_usuario_actualizacion_estado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Estado',
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mascota', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_mascota', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=10)),
                ('especie', models.CharField(max_length=50)),
                ('raza_mascota', models.CharField(blank=True, max_length=50, null=True)),
                ('edad_mascota', models.IntegerField(blank=True, null=True)),
                ('fecha_creacion_mascota', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_actualizacion_mascota', models.DateTimeField(auto_now=True, null=True)),
                ('id_usuario_creacion_mascota', models.IntegerField(blank=True, null=True)),
                ('id_usuario_actualizacion_mascota', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Mascota',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('descripcion_producto', models.TextField(blank=True, null=True)),
                ('categoria_producto', models.CharField(max_length=50)),
                ('precio_producto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('URL_imagen', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion_producto', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_actualizacion_producto', models.DateTimeField(auto_now=True, null=True)),
                ('id_usuario_creacion_producto', models.IntegerField(blank=True, null=True)),
                ('id_usuario_actualizacion_producto', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Producto',
            },
        ),
        migrations.CreateModel(
            name='Detalle_compra',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_detalle', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal_detalle', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_creacion_detallecompra', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_actualizacion_detallecompra', models.DateTimeField(auto_now=True, null=True)),
                ('id_usuario_creacion_detallecompra', models.IntegerField(blank=True, null=True)),
                ('id_usuario_actualizacion_detallecompra', models.IntegerField(blank=True, null=True)),
                ('id_compra', models.ForeignKey(db_column='id_compra', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='api.compra')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_compra', to='api.producto')),
            ],
            options={
                'db_table': 'Detalle_compra',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('imagen_rol', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion_rol', models.CharField(max_length=100)),
                ('fecha_creacion_rol', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_actualizacion_rol', models.DateTimeField(auto_now=True, null=True)),
                ('id_usuario_creacion_rol', models.IntegerField(blank=True, null=True)),
                ('id_usuario_actualizacion_rol', models.IntegerField(blank=True, null=True)),
                ('id_estado', models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.PROTECT, related_name='roles', to='api.estado')),
            ],
            options={
                'db_table': 'Rol',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id_turno', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_turno', models.DateField()),
                ('hora_turno', models.TimeField()),
                ('fecha_creacion_turno', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_actualizacion_turno', models.DateTimeField(auto_now=True, null=True)),
                ('id_usuario_creacion_turno', models.IntegerField(blank=True, null=True)),
                ('id_usuario_actualizacion_turno', models.IntegerField(blank=True, null=True)),
                ('id_agenda', models.ForeignKey(db_column='id_agenda', on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='api.agenda')),
                ('id_estado', models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.PROTECT, related_name='turnos', to='api.estado')),
                ('id_mascota', models.ForeignKey(db_column='id_mascota', on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='api.mascota')),
            ],
            options={
                'db_table': 'Turno',
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id_consulta', models.AutoField(primary_key=True, serialize=False)),
                ('diagnostico_consulta', models.TextField(blank=True, null=True)),
                ('prescripcion_consulta', models.TextField(blank=True, null=True)),
                ('observacion_consulta', models.TextField(blank=True, null=True)),
                ('fecha_creacion_consulta', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_actualizacion_consulta', models.DateTimeField(auto_now=True, null=True)),
                ('id_usuario_creacion_consulta', models.IntegerField(blank=True, null=True)),
                ('id_usuario_actualizacion_consulta', models.IntegerField(blank=True, null=True)),
                ('id_turno', models.ForeignKey(db_column='id_turno', on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='api.turno')),
            ],
            options={
                'db_table': 'Consulta',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('fecha_creacion_usuario', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_actualizacion_usuario', models.DateTimeField(auto_now=True, null=True)),
                ('id_usuario_creacion', models.IntegerField(blank=True, null=True)),
                ('id_usuario_actualizacion', models.IntegerField(blank=True, null=True)),
                ('id_rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='api.rol')),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
        migrations.AddField(
            model_name='turno',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='api.usuario'),
        ),
        migrations.AddField(
            model_name='producto',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='api.usuario'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='api.usuario'),
        ),
        migrations.AddField(
            model_name='compra',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='api.usuario'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='api.usuario'),
        ),
    ]
