# Generated by Django 5.2.8 on 2026-01-04 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_historialusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda',
            name='fin_almuerzo',
        ),
        migrations.RemoveField(
            model_name='agenda',
            name='inicio_almuerzo',
        ),
    ]
