# Generated by Django 5.2.8 on 2026-01-18 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_agenda_fin_almuerzo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_actividad', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_estado', models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='api.estado')),
            ],
            options={
                'db_table': 'Actividad',
            },
        ),
        migrations.CreateModel(
            name='DoctorActividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctores', to='api.actividad')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_asignadas', to='api.usuario')),
            ],
            options={
                'db_table': 'Doctor_Actividad',
                'unique_together': {('doctor', 'actividad')},
            },
        ),
    ]
