# Generated by Django 5.2.8 on 2026-01-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_actividad_doctoractividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='edad_meses',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
