# Generated by Django 5.2.8 on 2026-01-18 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_mascota_edad_meses'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='id_estado',
            field=models.ForeignKey(blank=True, db_column='id_estado', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='api.estado'),
        ),
    ]
