# Generated by Django 5.2.8 on 2026-01-18 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_producto_id_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='URL_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
