# Generated by Django 5.2.8 on 2026-01-19 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_producto_url_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_producto',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
