# Generated by Django 5.2.8 on 2026-01-19 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_producto_stock_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='id_estado',
        ),
    ]
