# Generated by Django 5.2.8 on 2026-01-20 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_producto_id_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega_estimada', models.DateTimeField(blank=True, null=True)),
                ('total_reserva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codigo_factura', models.CharField(max_length=20, unique=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True)),
                ('id_usuario_creacion', models.IntegerField(blank=True, null=True)),
                ('id_usuario_actualizacion', models.IntegerField(blank=True, null=True)),
                ('id_estado', models.ForeignKey(db_column='id_estado', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='api.estado')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='api.usuario')),
            ],
            options={
                'db_table': 'Reserva',
                'ordering': ['-fecha_reserva'],
            },
        ),
        migrations.CreateModel(
            name='DetalleReserva',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True)),
                ('id_usuario_creacion', models.IntegerField(blank=True, null=True)),
                ('id_usuario_actualizacion', models.IntegerField(blank=True, null=True)),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, related_name='reservas_detalle', to='api.producto')),
                ('id_reserva', models.ForeignKey(db_column='id_reserva', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='api.reserva')),
            ],
            options={
                'db_table': 'DetalleReserva',
            },
        ),
    ]
